spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dawnoneline
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      default_batch_fetch_size: 1000
      ddl-auto: update
  logging:
    level:
      org:
        SQL: debug
